/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      "colors": {
        "tertiary": "#924700",
        "outline": "var(--color-outline)",
        "surface-container": "#ecedf7",
        "secondary-fixed": "#e9ddff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e2ec",
        "on-background": "var(--color-on-background)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-primary-container": "#fefcff",
        "primary-fixed-dim": "#adc6ff",
        "secondary": "#6b38d4",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001a42",
        "surface-container-low": "#f2f3fd",
        "surface-variant": "#e1e2ec",
        "primary-container": "#2170e4",
        "tertiary-fixed-dim": "#ffb786",
        "secondary-fixed-dim": "#d0bcff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#5516be",
        "outline-variant": "#c2c6d6",
        "tertiary-fixed": "#ffdcc6",
        "surface-bright": "#f9f9ff",
        "on-primary": "var(--color-on-primary)",
        "on-surface": "var(--color-on-surface)",
        "error-container": "#ffdad6",
        "primary": "var(--color-primary)",
        "inverse-surface": "#2e3038",
        "background": "var(--color-background)",
        "on-secondary": "#ffffff",
        "tertiary-container": "#b75b00",
        "on-tertiary-fixed-variant": "#723600",
        "inverse-on-surface": "#eff0fa",
        "on-secondary-fixed": "#23005c",
        "on-primary-fixed-variant": "#004395",
        "on-secondary-container": "#fffbff",
        "primary-fixed": "#d8e2ff",
        "surface-tint": "#005ac2",
        "on-tertiary-fixed": "#311400",
        "surface-container-high": "#e6e7f2",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#8455ef",
        "surface-dim": "#d8d9e3",
        "surface": "var(--color-surface)",
        "inverse-primary": "#adc6ff",
        "on-tertiary-container": "#fffbff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "xxl": "2rem",
        "3xl": "1.5rem"
      },
      "spacing": {
        "lg": "1.5rem",
        "container-padding": "2.5rem",
        "md": "1rem",
        "unit": "4px",
        "sm": "0.5rem",
        "xxl": "3rem",
        "gutter": "1.5rem",
        "xs": "0.25rem",
        "xl": "2rem"
      },
      "fontFamily": {
        "inter": ["Inter", "sans-serif"],
        "body-sm": ["Inter"],
        "label-bold": ["Inter"],
        "h3-sub": ["Inter"],
        "h2-header": ["Inter"],
        "button-text": ["Inter"],
        "h1-display": ["Inter"],
        "body-lg": ["Inter"]
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
