export const MOCK_PROJECTS = [
  {
    id: "1",
    name: "Brand Identity 2024",
    description: "Ridefinizione completa dell'immagine coordinata per il lancio internazionale del Q3.",
    progress: 65,
    status: "Attivo",
    category: "Sviluppo Web",
    started_at: "12 Gen 2024",
    members_count: 12,
  },
  {
    id: "2",
    name: "E-commerce Portal",
    description: "Sviluppo piattaforma B2B con integrazione pagamenti e gestione logistica automatizzata.",
    progress: 32,
    status: "Attivo",
    category: "E-commerce",
    started_at: "05 Mar 2024",
    members_count: 5,
  },
  {
    id: "3",
    name: "Audit Sicurezza",
    description: "Revisione completa dei protocolli di accesso e crittografia dati per compliance GDPR.",
    progress: 100,
    status: "Completato",
    category: "Cybersecurity",
    started_at: "10 Dic 2023",
    members_count: 2,
  },
];

export const MOCK_TASKS = [
  {
    id: "1",
    title: "Analisi Requirement",
    description: "Revisione specifica tecnica v2.4",
    status: "Da fare",
    priority: "Alta",
    due_date: "12 Ott, 2023",
    time: "14:30 - 15:30",
    risk: 25,
  },
  {
    id: "2",
    title: "Sync Creative",
    description: "Discussione moodboard nuovo brand",
    status: "In corso",
    priority: "Media",
    due_date: "Oggi",
    time: "16:00 - 17:00",
    risk: 10,
  },
  {
    id: "3",
    title: "Daily Standup",
    description: "Aggiornamento team sviluppo",
    status: "Completato",
    priority: "Bassa",
    due_date: "08 Ott, 2023",
    time: "09:30 - 10:00",
    risk: 0,
  },
];
